// Generated by LiveScript 1.2.0
var app, r;
app = new Vue({
  el: '#todoapp',
  data: {
    title: '',
    activeFilter: 'all',
    all: JSON.parse(localStorage.getItem('v')) || []
  },
  ready: function(){
    this.$watch('all', function(it){
      return localStorage.v = JSON.stringify(it);
    }, true);
  },
  directives: {
    select: function(it){
      if (it) {
        return this.el.select();
      }
    }
  },
  computed: {
    active: function(){
      return _.reject(function(it){
        return it.completed;
      }, this.all);
    },
    completed: function(){
      return _.filter(function(it){
        return it.completed;
      }, this.all);
    },
    filtered: function(){
      return this[this.activeFilter];
    },
    allDone: {
      get: function(){
        return this.active.length === 0;
      },
      set: function(v){
        return _.each(function(it){
          return it.completed = v;
        }, this.all);
      }
    }
  },
  methods: {
    create: function(){
      var that;
      if (that = this.title.trim()) {
        this.all.push({
          title: that,
          completed: false,
          oldTitle: false
        });
        this.title = '';
      }
    },
    remove: function(it){
      this.all.$remove(it.$data);
    },
    edit: function(it){
      it.oldTitle = it.title;
    },
    cancel: function(it){
      it.title = it.oldTitle;
      it.oldTitle = '';
    },
    save: function(it){
      it.oldTitle = '';
      if (!it.title.trim()) {
        this.remove(it);
      }
    },
    removeCompleted: function(){
      this.all = _.reject(function(it){
        return it.completed;
      }, this.all);
    }
  }
});
r = Router({
  '*': function(it){
    return app.activeFilter = it;
  }
}).init('/all');