// Generated by LiveScript 1.2.0
var app;
app = new Vue({
  el: '#todoapp',
  data: {
    name: '',
    activeFilter: 'all',
    all: JSON.parse(localStorage.getItem('v')) || []
  },
  ready: function(){
    return this.$watch('all', function(it){
      return localStorage.v = JSON.stringify(it);
    }, {
      deep: true
    });
  },
  computed: {
    completed: function(){
      return _.filter(function(it){
        return it.completed;
      })(
      this.all);
    },
    active: function(){
      return _.reject(function(it){
        return it.completed;
      })(
      this.all);
    },
    allDone: {
      get: function(){
        return this.active.length === 0;
      },
      set: function(v){
        return _.each(function(it){
          return it.completed = v;
        })(
        this.all);
      }
    }
  },
  methods: {
    create: function(){
      var that;
      if (that = this.name.trim()) {
        this.all.push({
          name: that,
          completed: false,
          oldName: false
        });
        return this.name = '';
      }
    },
    cancel: function(it){
      it.name = it.oldName;
      return it.oldName = '';
    },
    save: function(it){
      it.oldName = '';
      if (!it.name.trim()) {
        return this.all.$remove(it);
      }
    },
    removeCompleted: function(){
      return this.all = _.reject(function(it){
        return it.completed;
      })(this.all);
    }
  }
});
Router({
  '*': function(it){
    return app.activeFilter = it;
  }
}).init('/all');